services:
    backend_builder:
        build:
            context: .
            dockerfile: Backend/Dockerfile
        image: backend:latest

    frontend_builder:
        build:
            context: .
            dockerfile: Frontend/Dockerfile
        image: frontend:latest

    backend:
        image: backend:latest
        container_name: backend
        volumes:
            - ./Backend/src:/app/src
            - ./Backend/start.py:/app/start.py
        depends_on:
            - backend_builder
            - db
            - redis
        working_dir: /app
        ports:
            - "8000:8000"
        environment:
            - DB_HOST=db
            - DB_PORT=5432
            - DB_NAME=mpt_db
            - DB_USER=mpt_user
            - DB_PASSWORD=mpt_pass
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        command: ["/bin/bash", "-c", "pipenv run python start.py"]

    db:
        build:
            context: .
            dockerfile: Postgres/Dockerfile
        image: db:latest
        container_name: postgres_db
        volumes:
            - pg_data:/var/lib/postgresql/data
            - ./Postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
            - POSTGRES_DB=mpt_db
            - POSTGRES_USER=mpt_user
            - POSTGRES_PASSWORD=mpt_pass
        ports:
            - "5432:5432"

    redis:
        image: redis:alpine
        container_name: redis_cache
        volumes:
            - redis_data:/data
        ports:
            - "6379:6379"

    frontend:
        image: frontend:latest
        container_name: frontend
        volumes:
            - ./Frontend/forms/src:/app/src
            - ./Frontend/forms/public:/app/public
        depends_on:
            - frontend_builder
        working_dir: /app
        ports:
            - "3000:3000"
        command: ["/bin/bash", "-c", "npm run start"]


    backend_tests:
        image: backend:latest
        container_name: backend_tests
        volumes:
            - ./Backend:/app
        depends_on:
            - backend_builder
            - db
            - redis
        working_dir: /app
        ports:
            - "8001:8000"
        environment:
            - DB_HOST=db
            - DB_PORT=5432
            - DB_NAME=mpt_db
            - DB_USER=mpt_user
            - DB_PASSWORD=mpt_pass
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        command: ["/bin/bash", "-c", "pipenv run pytest tests -v -s"]

    # frontend_tests:
    #     build:
    #         context: .
    #         dockerfile: Frontend/tests/Dockerfile
    #     image: frontend_tests:latest
    #     container_name: frontend_tests
    #     depends_on:
    #         - frontend
    #     working_dir: /tests
    #     environment:
    #         - DISPLAY=${DISPLAY}
    #     volumes:
    #         - /tmp/.X11-unix:/tmp/.X11-unix
    #     command: ["pytest", "-v", "start.py"]


volumes:
    pg_data:
    redis_data: